env: "dev"
storage_path: "./storage.db"
http_server:
  address: ":8080"
  timeout: 6s
  idle_timeout: 60s
  user: "admin"
  password: "admin"
connection_db:
  username: "admin"
  password: "admin"
  db_name: "url_short_db"
  sslmode: "disable"
  host: "localhost"
  port: "5432"
  max_pool_conn: 5